# Generated by Django 5.1.5 on 2025-01-17 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chai_varity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('Chai_var', models.CharField(choices=[('PT', 'Plane Tea'), ('MC', 'Masala chai'), ('GC', 'Ginger chai'), ('LC', 'Lemon chai'), ('EC', 'Elaichi chai'), ('GT', 'Green Tea'), ('BT', 'Black Tea'), ('KC', 'Kulhad Chai')], default='ML', max_length=2)),
            ],
        ),
    ]
